// ============================================================
// data.js — All static content: translations, jobs, schemes
// Author: Rozar Team | Built for Convolve 4.0 / AI Ignite 2026
// ============================================================

window.ROZAR_DATA = {};

// ─────────────────────────────────────────────
// TRANSLATIONS
// ─────────────────────────────────────────────
ROZAR_DATA.translations = {
  en: {
    font: "'Plus Jakarta Sans', sans-serif",
    fontClass: "font-en",
    nav: {
      home: "Home",
      jobs: "Job Matcher",
      schemes: "Schemes Hub",
      docs: "Documents",
      tutorials: "Tutorials",
      tech: "Tech & Impact",
      login: "Login",
      logout: "Logout",
      dashboard: "Dashboard",
    },
    hero: {
      badge: "🚀 India's First Vernacular Agentic Workforce AI",
      title: "Your Dream Job,",
      titleHighlight: "In Your Language",
      subtitle:
        "Rozar helps 450 million informal workers find jobs, get trained, and access government schemes — all in their mother tongue, over a simple phone call.",
      cta: "Call Rozar Now",
      ctaSecondary: "Watch Demo",
      trustedBy: "Trusted by workers across India",
    },
    dashboard: {
      welcome: "Welcome back",
      jobsApplied: "Jobs Applied",
      schemesEligible: "Schemes Eligible",
      trainingScheduled: "Training Scheduled",
      recentActivity: "Recent Activity",
      quickActions: "Quick Actions",
      findJobs: "Find Jobs",
      checkSchemes: "Check Schemes",
      uploadDocs: "Upload Docs",
      startTraining: "Start Training",
    },
    jobs: {
      title: "Job Matcher",
      subtitle: "AI-matched jobs based on your skills and location",
      autoApply: "Auto Apply",
      applyNow: "Apply Now",
      salary: "Salary",
      location: "Location",
      requirements: "Requirements",
      matchScore: "Match",
      applied: "Applied ✓",
    },
    schemes: {
      title: "Government Schemes Hub",
      subtitle: "Find and apply for schemes you are eligible for",
      checkEligibility: "Check Eligibility",
      applyNow: "Apply Now",
      viewSteps: "View Steps",
      eligible: "Eligible",
      amount: "Benefit Amount",
    },
    docs: {
      title: "Document Assistant",
      subtitle: "Upload your documents — we'll do the rest",
      dragDrop: "Drag & drop your Aadhaar or PAN card here",
      orClick: "or click to browse",
      uploading: "Extracting data with AI...",
      extracted: "Data Extracted Successfully!",
      name: "Name",
      dob: "Date of Birth",
      address: "Address",
      aadhaarNo: "Aadhaar Number",
    },
    tutorials: {
      title: "How-To Tutorials",
      subtitle: "Step-by-step guides to get your first job online",
    },
    chatbot: {
      placeholder: "Type your message...",
      send: "Send",
      voiceMode: "Voice Mode",
      thinking: "Rozar is thinking...",
      agents: {
        receptionist: "Receptionist",
        jobMatcher: "Job Matcher",
        docAssistant: "Document Assistant",
        schemeNavigator: "Scheme Navigator",
      },
      greeting:
        "Hello! I am Rozar, your personal career agent. How can I help you today? You can ask me about jobs, government schemes, or document help.",
    },
    login: {
      title: "Login to Rozar",
      email: "Email",
      password: "Password",
      loginBtn: "Login",
      demoBtn: "Login as Demo User",
      demoNote: "Demo: demo@rozar.in / rozar123",
    },
  },

  hi: {
    font: "'Noto Sans Devanagari', sans-serif",
    fontClass: "font-hi",
    nav: {
      home: "होम",
      jobs: "जॉब मैचर",
      schemes: "सरकारी योजनाएं",
      docs: "दस्तावेज़",
      tutorials: "ट्यूटोरियल",
      tech: "तकनीक और प्रभाव",
      login: "लॉगिन",
      logout: "लॉगआउट",
      dashboard: "डैशबोर्ड",
    },
    hero: {
      badge: "🚀 भारत का पहला वर्नाकुलर एजेंटिक वर्कफोर्स AI",
      title: "आपका सपनों का काम,",
      titleHighlight: "आपकी भाषा में",
      subtitle:
        "रोज़ार 45 करोड़ असंगठित मजदूरों को उनकी मातृभाषा में — बस एक फोन कॉल पर — नौकरी, ट्रेनिंग और सरकारी योजनाओं तक पहुंचाता है।",
      cta: "रोज़ार को कॉल करें",
      ctaSecondary: "डेमो देखें",
      trustedBy: "पूरे भारत के मजदूरों का विश्वास",
    },
    dashboard: {
      welcome: "वापसी पर स्वागत है",
      jobsApplied: "आवेदित नौकरियां",
      schemesEligible: "पात्र योजनाएं",
      trainingScheduled: "निर्धारित प्रशिक्षण",
      recentActivity: "हाल की गतिविधि",
      quickActions: "त्वरित कार्य",
      findJobs: "नौकरी खोजें",
      checkSchemes: "योजनाएं देखें",
      uploadDocs: "दस्तावेज़ अपलोड करें",
      startTraining: "प्रशिक्षण शुरू करें",
    },
    jobs: {
      title: "जॉब मैचर",
      subtitle: "आपके कौशल और स्थान के आधार पर AI-मिलान की गई नौकरियां",
      autoApply: "ऑटो अप्लाई",
      applyNow: "अभी अप्लाई करें",
      salary: "वेतन",
      location: "स्थान",
      requirements: "आवश्यकताएं",
      matchScore: "मिलान",
      applied: "आवेदित ✓",
    },
    schemes: {
      title: "सरकारी योजनाएं हब",
      subtitle: "वो योजनाएं खोजें और आवेदन करें जिनके लिए आप पात्र हैं",
      checkEligibility: "पात्रता जांचें",
      applyNow: "अभी आवेदन करें",
      viewSteps: "चरण देखें",
      eligible: "पात्र",
      amount: "लाभ राशि",
    },
    docs: {
      title: "दस्तावेज़ सहायक",
      subtitle: "अपने दस्तावेज़ अपलोड करें — बाकी हम करेंगे",
      dragDrop: "अपना आधार या PAN कार्ड यहाँ खींचें और छोड़ें",
      orClick: "या ब्राउज़ करने के लिए क्लिक करें",
      uploading: "AI से डेटा निकाला जा रहा है...",
      extracted: "डेटा सफलतापूर्वक निकाला गया!",
      name: "नाम",
      dob: "जन्म तिथि",
      address: "पता",
      aadhaarNo: "आधार नंबर",
    },
    tutorials: {
      title: "कैसे करें ट्यूटोरियल",
      subtitle: "ऑनलाइन पहली नौकरी पाने के लिए चरण-दर-चरण गाइड",
    },
    chatbot: {
      placeholder: "अपना संदेश लिखें...",
      send: "भेजें",
      voiceMode: "वॉइस मोड",
      thinking: "रोज़ार सोच रहा है...",
      agents: {
        receptionist: "रिसेप्शनिस्ट",
        jobMatcher: "जॉब मैचर",
        docAssistant: "दस्तावेज़ सहायक",
        schemeNavigator: "योजना नेविगेटर",
      },
      greeting:
        "नमस्ते! मैं रोज़ार हूं, आपका पर्सनल करियर एजेंट। आज मैं आपकी कैसे मदद कर सकता हूं? आप मुझसे नौकरी, सरकारी योजना, या दस्तावेज़ के बारे में पूछ सकते हैं।",
    },
    login: {
      title: "रोज़ार में लॉगिन करें",
      email: "ईमेल",
      password: "पासवर्ड",
      loginBtn: "लॉगिन",
      demoBtn: "डेमो यूज़र के रूप में लॉगिन",
      demoNote: "डेमो: demo@rozar.in / rozar123",
    },
  },

  ta: {
    font: "'Noto Sans Tamil', sans-serif",
    fontClass: "font-ta",
    nav: {
      home: "முகப்பு",
      jobs: "வேலை தேடல்",
      schemes: "அரசு திட்டங்கள்",
      docs: "ஆவணங்கள்",
      tutorials: "பயிற்சிகள்",
      tech: "தொழில்நுட்பம்",
      login: "உள்நுழை",
      logout: "வெளியேறு",
      dashboard: "டாஷ்போர்டு",
    },
    hero: {
      badge: "🚀 இந்தியாவின் முதல் வர்னாகுலர் AI தொழிலாளர் தளம்",
      title: "உங்கள் கனவு வேலை,",
      titleHighlight: "உங்கள் மொழியில்",
      subtitle:
        "ரோஸார் 45 கோடி தொழிலாளர்களுக்கு அவர்கள் தாய்மொழியில் — ஒரு தொலைபேசி அழைப்பில் — வேலை, பயிற்சி மற்றும் அரசு திட்டங்களை வழங்குகிறது.",
      cta: "ரோஸாரை அழையுங்கள்",
      ctaSecondary: "டெமோ பார்க்கவும்",
      trustedBy: "இந்தியா முழுவதும் தொழிலாளர்களின் நம்பிக்கை",
    },
    dashboard: {
      welcome: "மீண்டும் வரவேற்கிறோம்",
      jobsApplied: "விண்ணப்பித்த வேலைகள்",
      schemesEligible: "தகுதியான திட்டங்கள்",
      trainingScheduled: "திட்டமிட்ட பயிற்சி",
      recentActivity: "சமீபத்திய செயல்பாடு",
      quickActions: "விரைவு செயல்கள்",
      findJobs: "வேலை தேடு",
      checkSchemes: "திட்டங்கள் பார்",
      uploadDocs: "ஆவணங்கள் பதிவேற்று",
      startTraining: "பயிற்சி தொடங்கு",
    },
    jobs: {
      title: "வேலை தேடல்",
      subtitle: "உங்கள் திறமை மற்றும் இடம் அடிப்படையில் AI பொருத்தப்பட்ட வேலைகள்",
      autoApply: "தானியங்கி விண்ணப்பம்",
      applyNow: "இப்போது விண்ணப்பிக்கவும்",
      salary: "சம்பளம்",
      location: "இடம்",
      requirements: "தேவைகள்",
      matchScore: "பொருத்தம்",
      applied: "விண்ணப்பித்தது ✓",
    },
    schemes: {
      title: "அரசு திட்டங்கள் மையம்",
      subtitle: "நீங்கள் தகுதியான திட்டங்களை கண்டறிந்து விண்ணப்பிக்கவும்",
      checkEligibility: "தகுதி சரிபார்",
      applyNow: "இப்போது விண்ணப்பிக்கவும்",
      viewSteps: "படிகளை பார்",
      eligible: "தகுதியானவர்",
      amount: "பயன் தொகை",
    },
    docs: {
      title: "ஆவண உதவியாளர்",
      subtitle: "உங்கள் ஆவணங்களை பதிவேற்றுங்கள் — மீதி நாங்கள் செய்வோம்",
      dragDrop: "உங்கள் ஆதார் அல்லது PAN அட்டையை இங்கே இழுத்து விடுங்கள்",
      orClick: "அல்லது உலாவ கிளிக் செய்யுங்கள்",
      uploading: "AI மூலம் தரவு பிரித்தெடுக்கப்படுகிறது...",
      extracted: "தரவு வெற்றிகரமாக பிரித்தெடுக்கப்பட்டது!",
      name: "பெயர்",
      dob: "பிறந்த தேதி",
      address: "முகவரி",
      aadhaarNo: "ஆதார் எண்",
    },
    tutorials: {
      title: "எப்படி செய்வது பயிற்சிகள்",
      subtitle: "ஆன்லைனில் முதல் வேலை பெற படிப்படியான வழிகாட்டிகள்",
    },
    chatbot: {
      placeholder: "உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...",
      send: "அனுப்பு",
      voiceMode: "குரல் முறை",
      thinking: "ரோஸார் யோசிக்கிறது...",
      agents: {
        receptionist: "வரவேற்பாளர்",
        jobMatcher: "வேலை பொருத்தி",
        docAssistant: "ஆவண உதவியாளர்",
        schemeNavigator: "திட்ட வழிகாட்டி",
      },
      greeting:
        "வணக்கம்! நான் ரோஸார், உங்கள் தனிப்பட்ட தொழில் முகவர். இன்று நான் உங்களுக்கு எப்படி உதவலாம்? வேலை, அரசு திட்டங்கள், அல்லது ஆவண உதவி பற்றி கேளுங்கள்.",
    },
    login: {
      title: "ரோஸாரில் உள்நுழைக",
      email: "மின்னஞ்சல்",
      password: "கடவுச்சொல்",
      loginBtn: "உள்நுழை",
      demoBtn: "டெமோ பயனராக உள்நுழை",
      demoNote: "டெமோ: demo@rozar.in / rozar123",
    },
  },
};

// ─────────────────────────────────────────────
// JOBS DATA
// ─────────────────────────────────────────────
ROZAR_DATA.jobs = [
  {
    id: 1,
    company: "Swiggy",
    logo: "🛵",
    color: "#FC8019",
    title: { en: "Delivery Partner", hi: "डिलीवरी पार्टनर", ta: "டெலிவரி பார்ட்னர்" },
    salary: { en: "₹18,000–₹25,000/month", hi: "₹18,000–₹25,000/माह", ta: "₹18,000–₹25,000/மாதம்" },
    location: { en: "Chennai, Mumbai, Delhi", hi: "चेन्नई, मुंबई, दिल्ली", ta: "சென்னை, மும்பை, டெல்லி" },
    req: { en: "Bike + Smartphone", hi: "बाइक + स्मार्टफोन", ta: "பைக் + ஸ்மார்ட்போன்" },
    match: 97,
    tags: ["No Experience", "Flexible Hours", "Weekly Pay"],
  },
  {
    id: 2,
    company: "Zomato",
    logo: "🍕",
    color: "#E23744",
    title: { en: "Food Delivery Executive", hi: "फूड डिलीवरी एग्जीक्यूटिव", ta: "உணவு டெலிவரி எக்ஸிகியூட்டிவ்" },
    salary: { en: "₹15,000–₹22,000/month", hi: "₹15,000–₹22,000/माह", ta: "₹15,000–₹22,000/மாதம்" },
    location: { en: "Bangalore, Hyderabad, Pune", hi: "बेंगलुरु, हैदराबाद, पुणे", ta: "பெங்களூரு, ஹைதராபாத், புனே" },
    req: { en: "2-Wheeler + DL", hi: "दोपहिया + DL", ta: "இரு சக்கர வாகனம் + DL" },
    match: 94,
    tags: ["Insurance", "Bonus", "Fuel Allowance"],
  },
  {
    id: 3,
    company: "Blinkit",
    logo: "⚡",
    color: "#F8D000",
    title: { en: "Quick Commerce Rider", hi: "क्विक कॉमर्स राइडर", ta: "விரைவு கொமர்ஸ் ரைடர்" },
    salary: { en: "₹20,000–₹28,000/month", hi: "₹20,000–₹28,000/माह", ta: "₹20,000–₹28,000/மாதம்" },
    location: { en: "Delhi NCR, Mumbai", hi: "दिल्ली NCR, मुंबई", ta: "டெல்லி NCR, மும்பை" },
    req: { en: "Bike + Android Phone", hi: "बाइक + एंड्रॉयड फोन", ta: "பைக் + ஆண்ட்ராய்டு போன்" },
    match: 91,
    tags: ["₹500 Daily Guarantee", "No Night Shifts"],
  },
  {
    id: 4,
    company: "Amazon Flex",
    logo: "📦",
    color: "#FF9900",
    title: { en: "Delivery Associate", hi: "डिलीवरी एसोसिएट", ta: "டெலிவரி அசோசியேட்" },
    salary: { en: "₹16,000–₹24,000/month", hi: "₹16,000–₹24,000/माह", ta: "₹16,000–₹24,000/மாதம்" },
    location: { en: "Pan India", hi: "पूरे भारत में", ta: "இந்தியா முழுவதும்" },
    req: { en: "Bike/Van + Smartphone", hi: "बाइक/वैन + स्मार्टफोन", ta: "பைக்/வேன் + ஸ்மார்ட்போன்" },
    match: 88,
    tags: ["PF + ESI", "Overtime Pay"],
  },
  {
    id: 5,
    company: "Urban Company",
    logo: "🔧",
    color: "#7B2FF7",
    title: { en: "Electrician / Plumber", hi: "इलेक्ट्रीशियन / प्लंबर", ta: "மின்சாரி / பம்பர்" },
    salary: { en: "₹25,000–₹45,000/month", hi: "₹25,000–₹45,000/माह", ta: "₹25,000–₹45,000/மாதம்" },
    location: { en: "All Metro Cities", hi: "सभी महानगर", ta: "அனைத்து பெருநகரங்கள்" },
    req: { en: "ITI Certificate preferred", hi: "ITI प्रमाणपत्र preferred", ta: "ITI சான்றிதழ் விரும்பப்படுகிறது" },
    match: 85,
    tags: ["High Demand", "Top Earner"],
  },
  {
    id: 6,
    company: "Porter",
    logo: "🚚",
    color: "#00A699",
    title: { en: "Mini Truck Driver", hi: "मिनी ट्रक ड्राइवर", ta: "மினி டிரக் ஓட்டுனர்" },
    salary: { en: "₹22,000–₹35,000/month", hi: "₹22,000–₹35,000/माह", ta: "₹22,000–₹35,000/மாதம்" },
    location: { en: "Bangalore, Chennai, Pune", hi: "बेंगलुरु, चेन्नई, पुणे", ta: "பெங்களூரு, சென்னை, புனே" },
    req: { en: "Commercial DL (LMV)", hi: "कमर्शियल DL (LMV)", ta: "வணிக DL (LMV)" },
    match: 82,
    tags: ["Daily Pay", "Route Flexibility"],
  },
  {
    id: 7,
    company: "Rapido",
    logo: "🏍️",
    color: "#FFDD00",
    title: { en: "Bike Taxi Captain", hi: "बाइक टैक्सी कैप्टन", ta: "பைக் டாக்சி கேப்டன்" },
    salary: { en: "₹12,000–₹20,000/month", hi: "₹12,000–₹20,000/माह", ta: "₹12,000–₹20,000/மாதம்" },
    location: { en: "Bangalore, Hyderabad", hi: "बेंगलुरु, हैदराबाद", ta: "பெங்களூரு, ஹைதராபாத்" },
    req: { en: "Bike + DL + Helmet", hi: "बाइक + DL + हेलमेट", ta: "பைக் + DL + ஹெல்மெட்" },
    match: 79,
    tags: ["Flexible", "Surge Earnings"],
  },
  {
    id: 8,
    company: "Shadowfax",
    logo: "🦊",
    color: "#6C47FF",
    title: { en: "Last Mile Delivery", hi: "लास्ट माइल डिलीवरी", ta: "கடைசி மைல் டெலிவரி" },
    salary: { en: "₹14,000–₹19,000/month", hi: "₹14,000–₹19,000/माह", ta: "₹14,000–₹19,000/மாதம்" },
    location: { en: "Tier 2 & Tier 3 Cities", hi: "टियर 2 और टियर 3 शहर", ta: "டயர் 2 மற்றும் டயர் 3 நகரங்கள்" },
    req: { en: "Any 2-Wheeler", hi: "कोई भी 2-व्हीलर", ta: "எந்த 2-சக்கர வாகனமும்" },
    match: 75,
    tags: ["Small Towns", "Steady Work"],
  },
];

// ─────────────────────────────────────────────
// GOVERNMENT SCHEMES
// ─────────────────────────────────────────────
ROZAR_DATA.schemes = [
  {
    id: "pmkvy",
    name: "PMKVY 4.0",
    fullName: {
      en: "Pradhan Mantri Kaushal Vikas Yojana",
      hi: "प्रधानमंत्री कौशल विकास योजना",
      ta: "பிரதான் மந்திரி கௌஷல் விகாஸ் யோஜனா",
    },
    emoji: "🎓",
    color: "#FF6700",
    benefit: { en: "Free Training + ₹8,000 stipend", hi: "मुफ्त ट्रेनिंग + ₹8,000 वजीफा", ta: "இலவச பயிற்சி + ₹8,000 உதவித்தொகை" },
    desc: {
      en: "Free skill training with government certification for unemployed youth",
      hi: "बेरोजगार युवाओं के लिए सरकारी सर्टिफिकेट के साथ मुफ्त कौशल प्रशिक्षण",
      ta: "வேலையில்லாத இளைஞர்களுக்கு அரசு சான்றிதழுடன் இலவச திறன் பயிற்சி",
    },
    steps: {
      en: ["Visit pmkvyofficial.org or nearest PMKVY center", "Register with Aadhaar + mobile number", "Choose your trade/skill from 300+ options", "Attend free training (15–90 days)", "Give assessment exam", "Receive certificate + job placement help"],
      hi: ["pmkvyofficial.org या नजदीकी PMKVY केंद्र जाएं", "आधार + मोबाइल नंबर से पंजीकरण करें", "300+ विकल्पों में से अपना कौशल चुनें", "मुफ्त ट्रेनिंग में भाग लें (15–90 दिन)", "मूल्यांकन परीक्षा दें", "सर्टिफिकेट + जॉब प्लेसमेंट सहायता पाएं"],
      ta: ["pmkvyofficial.org அல்லது அருகிலுள்ள PMKVY மையத்தை பார்வையிடுங்கள்", "ஆதார் + மொபைல் எண்ணுடன் பதிவு செய்யுங்கள்", "300+ விருப்பங்களில் இருந்து உங்கள் திறனை தேர்வு செய்யுங்கள்", "இலவச பயிற்சியில் கலந்து கொள்ளுங்கள் (15–90 நாட்கள்)", "மதிப்பீட்டு தேர்வு எழுதுங்கள்", "சான்றிதழ் + வேலை வாய்ப்பு உதவி பெறுங்கள்"],
    },
    eligibility: { en: "Age 15–45, Indian citizen, no formal employment", hi: "आयु 15–45, भारतीय नागरिक, कोई औपचारिक रोजगार नहीं", ta: "வயது 15–45, இந்திய குடிமகன், முறையான வேலை இல்லாதவர்" },
  },
  {
    id: "nrlm",
    name: "DAY-NRLM",
    fullName: {
      en: "Deendayal Antyodaya Yojana - NRLM",
      hi: "दीनदयाल अंत्योदय योजना - NRLM",
      ta: "தீன்தயால் அந்தியோதய யோஜனா - NRLM",
    },
    emoji: "🏘️",
    color: "#003087",
    benefit: { en: "Subsidized loans up to ₹3 lakh", hi: "₹3 लाख तक सब्सिडी ऋण", ta: "₹3 லட்சம் வரை மானிய கடன்" },
    desc: {
      en: "Self-help group support and livelihood promotion for rural poor",
      hi: "ग्रामीण गरीबों के लिए स्व-सहायता समूह और आजीविका प्रोत्साहन",
      ta: "கிராமப்புற ஏழைகளுக்கு சுய உதவி குழு ஆதரவு மற்றும் வாழ்வாதார ஊக்குவிப்பு",
    },
    steps: {
      en: ["Contact your nearest Block Development Officer", "Join or form a Self-Help Group (10–20 women)", "Open a bank account in group name", "Maintain savings + repayment discipline for 3 months", "Apply for Community Investment Fund", "Access loan after 6 months of good credit history"],
      hi: ["नजदीकी खंड विकास अधिकारी से संपर्क करें", "स्व-सहायता समूह में शामिल हों या बनाएं (10–20 महिलाएं)", "समूह के नाम पर बैंक खाता खोलें", "3 माह तक बचत + पुनर्भुगतान अनुशासन बनाए रखें", "सामुदायिक निवेश कोष के लिए आवेदन करें", "6 महीने के अच्छे क्रेडिट इतिहास के बाद ऋण प्राप्त करें"],
      ta: ["அருகிலுள்ள தொகுதி வளர்ச்சி அதிகாரியை தொடர்பு கொள்ளுங்கள்", "சுய உதவி குழுவில் சேருங்கள் அல்லது உருவாக்குங்கள் (10–20 பெண்கள்)", "குழு பெயரில் வங்கி கணக்கு திறக்கவும்", "3 மாதம் சேமிப்பு + திருப்பிச் செலுத்தும் ஒழுக்கம் பராமரிக்கவும்", "சமூக முதலீட்டு நிதிக்கு விண்ணப்பிக்கவும்", "6 மாத நல்ல கடன் வரலாற்றுக்கு பிறகு கடன் பெறவும்"],
    },
    eligibility: { en: "BPL families, rural women especially", hi: "BPL परिवार, विशेषकर ग्रामीण महिलाएं", ta: "BPL குடும்பங்கள், குறிப்பாக கிராமப்புற பெண்கள்" },
  },
  {
    id: "pmegp",
    name: "PMEGP",
    fullName: {
      en: "PM Employment Generation Programme",
      hi: "प्रधानमंत्री रोजगार सृजन कार्यक्रम",
      ta: "பிரதான் மந்திரி வேலைவாய்ப்பு உருவாக்க திட்டம்",
    },
    emoji: "🏭",
    color: "#16A34A",
    benefit: { en: "Up to 35% subsidy on project cost", hi: "परियोजना लागत पर 35% तक सब्सिडी", ta: "திட்ட செலவில் 35% வரை மானியம்" },
    desc: {
      en: "Start your own business with government subsidy on bank loan",
      hi: "बैंक ऋण पर सरकारी सब्सिडी से अपना व्यवसाय शुरू करें",
      ta: "வங்கி கடனில் அரசு மானியத்துடன் உங்கள் சொந்த தொழில் தொடங்குங்கள்",
    },
    steps: {
      en: ["Register on kviconline.gov.in", "Choose your business idea (manufacturing/service)", "Fill PMEGP application with project report", "Get EDP (Entrepreneur Development) training", "Bank processes loan (15–25 lakh max)", "Government releases 25–35% subsidy directly"],
      hi: ["kviconline.gov.in पर पंजीकरण करें", "अपना व्यवसाय विचार चुनें (निर्माण/सेवा)", "प्रोजेक्ट रिपोर्ट के साथ PMEGP आवेदन भरें", "EDP (उद्यमी विकास) प्रशिक्षण लें", "बैंक ऋण प्रक्रिया (अधिकतम 15–25 लाख)", "सरकार 25–35% सब्सिडी सीधे जारी करती है"],
      ta: ["kviconline.gov.in இல் பதிவு செய்யுங்கள்", "உங்கள் வணிக யோசனையை தேர்வு செய்யுங்கள் (உற்பத்தி/சேவை)", "திட்ட அறிக்கையுடன் PMEGP விண்ணப்பம் நிரப்புங்கள்", "EDP (தொழில்முனைவோர் வளர்ச்சி) பயிற்சி பெறுங்கள்", "வங்கி கடன் செயல்படுத்துகிறது (அதிகபட்சம் 15–25 லட்சம்)", "அரசு 25–35% மானியத்தை நேரடியாக வழங்குகிறது"],
    },
    eligibility: { en: "Age 18+, 8th pass minimum, no existing govt loan", hi: "आयु 18+, कम से कम 8वीं पास, कोई मौजूदा सरकारी ऋण नहीं", ta: "வயது 18+, குறைந்தது 8-ம் வகுப்பு தேர்ச்சி, தற்போது அரசு கடன் இல்லாதவர்" },
  },
  {
    id: "skillindia",
    name: "Skill India",
    fullName: {
      en: "Skill India Digital Mission",
      hi: "कौशल भारत डिजिटल मिशन",
      ta: "திறன் இந்தியா டிஜிட்டல் மிஷன்",
    },
    emoji: "💻",
    color: "#7C3AED",
    benefit: { en: "Free digital skills + placement", hi: "मुफ्त डिजिटल कौशल + प्लेसमेंट", ta: "இலவச டிஜிட்டல் திறன்கள் + வேலை வாய்ப்பு" },
    desc: {
      en: "Learn digital & vocational skills online for free with government certification",
      hi: "सरकारी सर्टिफिकेट के साथ ऑनलाइन डिजिटल और व्यावसायिक कौशल मुफ्त सीखें",
      ta: "அரசு சான்றிதழுடன் ஆன்லைனில் இலவசமாக டிஜிட்டல் மற்றும் தொழில் திறன்கள் கற்றுக்கொள்ளுங்கள்",
    },
    steps: {
      en: ["Download Skill India app or visit skillindia.gov.in", "Create account with mobile number", "Browse 500+ free courses in your language", "Complete course + pass assessment", "Download digital certificate", "Apply for jobs through Skill India portal"],
      hi: ["Skill India ऐप डाउनलोड करें या skillindia.gov.in जाएं", "मोबाइल नंबर से अकाउंट बनाएं", "अपनी भाषा में 500+ मुफ्त कोर्स ब्राउज़ करें", "कोर्स पूरा करें + मूल्यांकन पास करें", "डिजिटल सर्टिफिकेट डाउनलोड करें", "Skill India पोर्टल से नौकरियों के लिए अप्लाई करें"],
      ta: ["Skill India ஆப்பை பதிவிறக்கவும் அல்லது skillindia.gov.in பார்வையிடவும்", "மொபைல் எண்ணுடன் கணக்கு உருவாக்கவும்", "உங்கள் மொழியில் 500+ இலவச படிப்புகளை உலாவுங்கள்", "படிப்பை முடித்து மதிப்பீட்டில் தேர்ச்சி பெறுங்கள்", "டிஜிட்டல் சான்றிதழை பதிவிறக்கவும்", "Skill India போர்ட்டல் மூலம் வேலைகளுக்கு விண்ணப்பிக்கவும்"],
    },
    eligibility: { en: "Any Indian citizen, age 15+", hi: "कोई भी भारतीय नागरिक, आयु 15+", ta: "எந்த இந்திய குடிமகனும், வயது 15+" },
  },
  {
    id: "esic",
    name: "ESIC",
    fullName: {
      en: "Employee State Insurance Corporation",
      hi: "कर्मचारी राज्य बीमा निगम",
      ta: "ஊழியர் மாநில காப்பீட்டு கழகம்",
    },
    emoji: "🏥",
    color: "#DC2626",
    benefit: { en: "Free medical + sickness benefit", hi: "मुफ्त चिकित्सा + बीमारी लाभ", ta: "இலவச மருத்துவ + நோய் நலன்" },
    desc: {
      en: "Health insurance and social security for workers earning below ₹21,000/month",
      hi: "₹21,000/माह से कम कमाने वाले कर्मचारियों के लिए स्वास्थ्य बीमा और सामाजिक सुरक्षा",
      ta: "₹21,000/மாதம் கீழே சம்பாதிக்கும் தொழிலாளர்களுக்கு சுகாதார காப்பீடு மற்றும் சமூக பாதுகாப்பு",
    },
    steps: {
      en: ["Your employer must register with ESIC", "Get ESIC card with IP number", "Visit any ESIC dispensary/hospital for free treatment", "For sickness benefit: submit sick certificate from ESIC doctor", "Get 70% of daily wages during sickness (up to 91 days)", "Maternity benefit: 26 weeks full pay for women"],
      hi: ["आपके नियोक्ता को ESIC में पंजीकरण करना होगा", "IP नंबर के साथ ESIC कार्ड प्राप्त करें", "मुफ्त इलाज के लिए किसी भी ESIC डिस्पेंसरी/अस्पताल जाएं", "बीमारी लाभ के लिए: ESIC डॉक्टर से बीमारी प्रमाणपत्र जमा करें", "बीमारी के दौरान दैनिक मजदूरी का 70% पाएं (91 दिन तक)", "मातृत्व लाभ: महिलाओं के लिए 26 सप्ताह पूरा वेतन"],
      ta: ["உங்கள் முதலாளி ESIC இல் பதிவு செய்திருக்க வேண்டும்", "IP எண்ணுடன் ESIC அட்டை பெறுங்கள்", "இலவச சிகிச்சைக்கு எந்த ESIC மருந்தகம்/மருத்துவமனையும் பார்வையிடவும்", "நோய் நலனுக்கு: ESIC மருத்துவரிடம் இருந்து நோய் சான்றிதழ் சமர்ப்பிக்கவும்", "நோய்வாய்ப்படும் போது தினசரி கூலியில் 70% பெறுங்கள் (91 நாட்கள் வரை)", "மகப்பேறு நலன்: பெண்களுக்கு 26 வாரங்கள் முழு சம்பளம்"],
    },
    eligibility: { en: "Employees earning ≤ ₹21,000/month in registered firms", hi: "पंजीकृत फर्मों में ₹21,000/माह ≤ कमाने वाले कर्मचारी", ta: "பதிவுசெய்யப்பட்ட நிறுவனங்களில் ₹21,000/மாதம் ≤ சம்பாதிக்கும் ஊழியர்கள்" },
  },
  {
    id: "epfo",
    name: "EPFO",
    fullName: {
      en: "Employees Provident Fund",
      hi: "कर्मचारी भविष्य निधि",
      ta: "ஊழியர்கள் வருங்கால வைப்பு நிதி",
    },
    emoji: "💰",
    color: "#0369A1",
    benefit: { en: "Retirement + Pension + Insurance", hi: "सेवानिवृत्ति + पेंशन + बीमा", ta: "ஓய்வூதியம் + பென்ஷன் + காப்பீடு" },
    desc: {
      en: "Mandatory retirement savings with employer matching for all salaried employees",
      hi: "सभी वेतनभोगी कर्मचारियों के लिए नियोक्ता मिलान के साथ अनिवार्य सेवानिवृत्ति बचत",
      ta: "அனைத்து ஊதியம் பெறும் ஊழியர்களுக்கு முதலாளி இணைப்புடன் கட்டாய ஓய்வு சேமிப்பு",
    },
    steps: {
      en: ["Employer registers you on UAN portal automatically", "Activate your UAN number via umang app", "Employee contributes 12% of basic salary", "Employer matches 12% (3.67% EPF + 8.33% EPS)", "Check balance via EPFO portal / UMANG app", "Withdraw on retirement or job change (with rules)"],
      hi: ["नियोक्ता आपको UAN पोर्टल पर स्वचालित रूप से पंजीकृत करता है", "UMANG ऐप के माध्यम से अपना UAN नंबर सक्रिय करें", "कर्मचारी मूल वेतन का 12% योगदान देता है", "नियोक्ता 12% मिलाता है (3.67% EPF + 8.33% EPS)", "EPFO पोर्टल / UMANG ऐप के माध्यम से बैलेंस चेक करें", "सेवानिवृत्ति या नौकरी बदलने पर निकासी (नियमों के साथ)"],
      ta: ["முதலாளி உங்களை UAN போர்ட்டலில் தானாக பதிவு செய்கிறார்", "UMANG ஆப் மூலம் உங்கள் UAN எண்ணை செயல்படுத்துங்கள்", "ஊழியர் அடிப்படை சம்பளத்தில் 12% பங்களிக்கிறார்", "முதலாளி 12% இணைக்கிறார் (3.67% EPF + 8.33% EPS)", "EPFO போர்ட்டல் / UMANG ஆப் மூலம் இருப்பை சரிபார்க்கவும்", "ஓய்வு அல்லது வேலை மாற்றத்தில் திரும்பப் பெறுங்கள் (விதிகளுடன்)"],
    },
    eligibility: { en: "All employees in firms with 20+ workers", hi: "20+ कर्मचारियों वाली फर्मों में सभी कर्मचारी", ta: "20+ தொழிலாளர்கள் உள்ள நிறுவனங்களில் அனைத்து ஊழியர்களும்" },
  },
];

// ─────────────────────────────────────────────
// TUTORIALS DATA
// ─────────────────────────────────────────────
ROZAR_DATA.tutorials = [
  {
    id: "linkedin",
    icon: "💼",
    color: "#0077B5",
    title: { en: "Apply on LinkedIn", hi: "LinkedIn पर अप्लाई करें", ta: "LinkedIn இல் விண்ணப்பிக்கவும்" },
    steps: {
      en: ["Download LinkedIn from Play Store (free)", "Sign up with phone number or email", "Add your name, location, and job title (e.g. 'Driver')", "Upload a clear profile photo (important!)", "Search 'Delivery jobs near me' or 'Driver jobs Chennai'", "Click 'Easy Apply' button — takes only 2 minutes", "Track applications in 'My Jobs' section"],
      hi: ["Play Store से LinkedIn डाउनलोड करें (मुफ्त)", "फोन नंबर या ईमेल से साइन अप करें", "अपना नाम, स्थान और जॉब टाइटल जोड़ें (जैसे 'ड्राइवर')", "स्पष्ट प्रोफाइल फोटो अपलोड करें (जरूरी!)", "'Delivery jobs near me' या 'Driver jobs Delhi' खोजें", "'Easy Apply' बटन क्लिक करें — केवल 2 मिनट लगते हैं", "'My Jobs' सेक्शन में आवेदनों को ट्रैक करें"],
      ta: ["Play Store இலிருந்து LinkedIn பதிவிறக்கவும் (இலவசம்)", "தொலைபேசி எண் அல்லது மின்னஞ்சல் மூலம் பதிவு செய்யுங்கள்", "உங்கள் பெயர், இடம் மற்றும் வேலை தலைப்பை சேர்க்கவும் (எ.கா. 'ஓட்டுனர்')", "தெளிவான சுயவிவர புகைப்படத்தை பதிவேற்றுங்கள் (முக்கியம்!)", "'Delivery jobs near me' அல்லது 'Driver jobs Chennai' தேடுங்கள்", "'Easy Apply' பொத்தானை கிளிக் செய்யுங்கள் — 2 நிமிடங்கள் மட்டுமே", "'My Jobs' பகுதியில் விண்ணப்பங்களை கண்காணியுங்கள்"],
    },
  },
  {
    id: "naukri",
    icon: "📰",
    color: "#4A90D9",
    title: { en: "Apply on Naukri.com", hi: "Naukri.com पर अप्लाई करें", ta: "Naukri.com இல் விண்ணப்பிக்கவும்" },
    steps: {
      en: ["Go to naukri.com on your phone browser", "Click 'Register for Free'", "Fill basic details — takes 5 minutes", "Upload Aadhaar / school certificate as identity proof", "Use keyword: 'driving jobs' or 'delivery boy'", "Filter by city and salary range", "Apply and get SMS alerts on your phone"],
      hi: ["अपने फोन ब्राउज़र में naukri.com खोलें", "'Register for Free' क्लिक करें", "बेसिक डिटेल्स भरें — 5 मिनट लगते हैं", "पहचान प्रमाण के रूप में आधार / स्कूल सर्टिफिकेट अपलोड करें", "कीवर्ड का उपयोग करें: 'driving jobs' या 'delivery boy'", "शहर और वेतन सीमा से फिल्टर करें", "अप्लाई करें और अपने फोन पर SMS अलर्ट पाएं"],
      ta: ["உங்கள் தொலைபேசி உலாவியில் naukri.com திறக்கவும்", "'Register for Free' கிளிக் செய்யுங்கள்", "அடிப்படை விவரங்களை நிரப்புங்கள் — 5 நிமிடங்கள் ஆகும்", "அடையாள சான்றாக ஆதார் / பள்ளி சான்றிதழை பதிவேற்றுங்கள்", "முக்கிய வார்த்தை பயன்படுத்துங்கள்: 'driving jobs' அல்லது 'delivery boy'", "நகரம் மற்றும் சம்பள வரம்பால் வடிகட்டுங்கள்", "விண்ணப்பிக்கவும், உங்கள் தொலைபேசியில் SMS எச்சரிக்கை பெறுங்கள்"],
    },
  },
  {
    id: "apna",
    icon: "👥",
    color: "#6C47FF",
    title: { en: "Use Apna.co", hi: "Apna.co इस्तेमाल करें", ta: "Apna.co பயன்படுத்துங்கள்" },
    steps: {
      en: ["Download Apna app from Play Store", "Select your preferred language (Hindi/Tamil/English)", "Enter mobile number — OTP verification", "Select your skill (Driver, Delivery, Cook, etc.)", "App shows jobs within 5 km of your location", "One-tap apply — recruiter calls you directly!", "Join community of workers in your area"],
      hi: ["Play Store से Apna ऐप डाउनलोड करें", "अपनी पसंदीदा भाषा चुनें (हिंदी/तमिल/अंग्रेजी)", "मोबाइल नंबर दर्ज करें — OTP वेरिफिकेशन", "अपना कौशल चुनें (ड्राइवर, डिलीवरी, कुक, आदि)", "ऐप आपके स्थान के 5 किमी के भीतर नौकरियां दिखाता है", "एक-टैप अप्लाई — रिक्रूटर सीधे आपको कॉल करता है!", "अपने क्षेत्र में मजदूरों के समुदाय में शामिल हों"],
      ta: ["Play Store இலிருந்து Apna ஆப்பை பதிவிறக்கவும்", "உங்கள் விரும்பிய மொழியை தேர்வு செய்யுங்கள் (இந்தி/தமிழ்/ஆங்கிலம்)", "மொபைல் எண் உள்ளிடவும் — OTP சரிபார்ப்பு", "உங்கள் திறனை தேர்வு செய்யுங்கள் (ஓட்டுனர், டெலிவரி, சமையல்காரர், முதலியன)", "ஆப் உங்கள் இடத்திலிருந்து 5 கிமீ தொலைவில் வேலைகளை காட்டுகிறது", "ஒரு-தட்டல் விண்ணப்பம் — ஆட்சேர்ப்பாளர் நேரடியாக உங்களை அழைக்கிறார்!", "உங்கள் பகுதியில் தொழிலாளர்களின் சமூகத்தில் சேருங்கள்"],
    },
  },
  {
    id: "whatsapp",
    icon: "💬",
    color: "#25D366",
    title: { en: "WhatsApp Resume", hi: "WhatsApp रिज़्यूमे", ta: "WhatsApp ரெஸ்யூமே" },
    steps: {
      en: ["Open WhatsApp — go to Status tab", "Type your skills and experience as a status", "Example: '5 yrs delivery exp | Own bike | Available immediately | Call: 98XXXXXX'", "Add your photo to make it professional", "Share in local job WhatsApp groups", "Save contacts of recruiters who message you", "Reply fast — opportunities go in 24 hours!"],
      hi: ["WhatsApp खोलें — Status टैब पर जाएं", "अपने कौशल और अनुभव को स्टेटस के रूप में टाइप करें", "उदाहरण: '5 साल डिलीवरी अनुभव | खुद की बाइक | तुरंत उपलब्ध | कॉल: 98XXXXXX'", "प्रोफेशनल दिखने के लिए अपनी फोटो जोड़ें", "स्थानीय जॉब WhatsApp ग्रुप में शेयर करें", "जो रिक्रूटर मैसेज करें उनके कॉन्टैक्ट सेव करें", "जल्दी जवाब दें — अवसर 24 घंटे में चले जाते हैं!"],
      ta: ["WhatsApp திறக்கவும் — Status தாவலுக்கு செல்லவும்", "உங்கள் திறன்கள் மற்றும் அனுபவத்தை நிலையாக தட்டச்சு செய்யுங்கள்", "உதாரணம்: '5 ஆண்டு டெலிவரி அனுபவம் | சொந்த பைக் | உடனே கிடைக்கும் | அழை: 98XXXXXX'", "தொழில்முறையாக காட்ட உங்கள் புகைப்படத்தை சேர்க்கவும்", "உள்ளூர் வேலை WhatsApp குழுக்களில் பகிரவும்", "செய்தி அனுப்பும் ஆட்சேர்ப்பாளர்களின் தொடர்புகளை சேமிக்கவும்", "விரைவாக பதிலளியுங்கள் — வாய்ப்புகள் 24 மணிநேரத்தில் போய்விடும்!"],
    },
  },
];

// ─────────────────────────────────────────────
// CHATBOT FLOWS (multi-lang demo conversation)
// ─────────────────────────────────────────────
ROZAR_DATA.chatFlows = {
  en: [
    { role: "user", text: "I want a delivery boy job" },
    { role: "bot", agent: "receptionist", text: "Great! I can help you find delivery jobs. What is your current city?" },
    { role: "user", text: "Chennai" },
    { role: "bot", agent: "jobMatcher", text: "Perfect! I found 3 top delivery jobs in Chennai — Swiggy (₹20K/month), Zomato (₹18K), and Blinkit (₹22K). Shall I apply to all three for you?" },
    { role: "user", text: "Yes apply" },
    { role: "bot", agent: "jobMatcher", text: "To apply, I need your Aadhaar card photo. Can you upload it? It takes 10 seconds." },
    { role: "user", text: "Ok I will upload" },
    { role: "bot", agent: "docAssistant", text: "✅ Aadhaar scanned! Name: Ravi Kumar, DOB: 15/03/1995, Address: Chennai, TN. All details auto-filled. Applying now..." },
    { role: "bot", agent: "jobMatcher", text: "🎉 Applied to Swiggy, Zomato & Blinkit! You'll get a call within 24–48 hours. Also, did you know you're eligible for PMKVY free training scheme worth ₹8,000?" },
    { role: "user", text: "Tell me about PMKVY" },
    { role: "bot", agent: "schemeNavigator", text: "PMKVY (Pradhan Mantri Kaushal Vikas Yojana) gives you free skill training for 15–90 days + ₹8,000 stipend + government certificate. Want me to apply for you?" },
  ],
  hi: [
    { role: "user", text: "मुझे डिलीवरी बॉय की जॉब चाहिए" },
    { role: "bot", agent: "receptionist", text: "बहुत अच्छा! मैं आपको डिलीवरी जॉब खोजने में मदद कर सकता हूं। आपका शहर कौन सा है?" },
    { role: "user", text: "चेन्नई" },
    { role: "bot", agent: "jobMatcher", text: "परफेक्ट! चेन्नई में 3 बेहतरीन डिलीवरी जॉब मिली — Swiggy (₹20K/माह), Zomato (₹18K), और Blinkit (₹22K)। क्या मैं तीनों में आपके लिए अप्लाई करूं?" },
    { role: "user", text: "हां अप्लाई करो" },
    { role: "bot", agent: "jobMatcher", text: "अप्लाई करने के लिए आपके आधार कार्ड की फोटो चाहिए। क्या आप अपलोड कर सकते हैं? 10 सेकंड लगेंगे।" },
    { role: "user", text: "ठीक है मैं अपलोड करूंगा" },
    { role: "bot", agent: "docAssistant", text: "✅ आधार स्कैन हो गया! नाम: रवि कुमार, जन्म तिथि: 15/03/1995, पता: चेन्नई, TN। सभी विवरण ऑटो-भर गए। अभी अप्लाई हो रहा है..." },
    { role: "bot", agent: "jobMatcher", text: "🎉 Swiggy, Zomato और Blinkit में अप्लाई हो गया! 24–48 घंटों में कॉल आएगा। क्या आप जानते हैं कि आप PMKVY मुफ्त ट्रेनिंग योजना के लिए पात्र हैं — ₹8,000 वजीफे के साथ?" },
    { role: "user", text: "PMKVY के बारे में बताओ" },
    { role: "bot", agent: "schemeNavigator", text: "PMKVY (प्रधानमंत्री कौशल विकास योजना) में 15–90 दिन की मुफ्त ट्रेनिंग + ₹8,000 वजीफा + सरकारी सर्टिफिकेट मिलता है। क्या मैं आपके लिए अप्लाई करूं?" },
  ],
  ta: [
    { role: "user", text: "எனக்கு டெலிவரி பாய் வேலை வேண்டும்" },
    { role: "bot", agent: "receptionist", text: "மிகவும் நல்லது! நான் உங்களுக்கு டெலிவரி வேலை கண்டுபிடிக்க உதவலாம். உங்கள் நகரம் எது?" },
    { role: "user", text: "சென்னை" },
    { role: "bot", agent: "jobMatcher", text: "சிறப்பு! சென்னையில் 3 சிறந்த டெலிவரி வேலைகள் கிடைத்தன — Swiggy (₹20K/மாதம்), Zomato (₹18K), மற்றும் Blinkit (₹22K). மூன்றிலும் உங்களுக்காக விண்ணப்பிக்கட்டுமா?" },
    { role: "user", text: "ஆம் விண்ணப்பிக்கவும்" },
    { role: "bot", agent: "jobMatcher", text: "விண்ணப்பிக்க உங்கள் ஆதார் அட்டை புகைப்படம் தேவை. பதிவேற்ற முடியுமா? 10 விநாடிகள் ஆகும்." },
    { role: "user", text: "சரி நான் பதிவேற்றுகிறேன்" },
    { role: "bot", agent: "docAssistant", text: "✅ ஆதார் ஸ்கேன் செய்யப்பட்டது! பெயர்: ரவி குமார், பிறந்த தேதி: 15/03/1995, முகவரி: சென்னை, TN. அனைத்து விவரங்களும் தானாக நிரப்பப்பட்டன. இப்போது விண்ணப்பிக்கிறேன்..." },
    { role: "bot", agent: "jobMatcher", text: "🎉 Swiggy, Zomato மற்றும் Blinkit இல் விண்ணப்பிக்கப்பட்டது! 24–48 மணிநேரத்தில் அழைப்பு வரும். மேலும், ₹8,000 உதவித்தொகையுடன் PMKVY இலவச பயிற்சி திட்டத்திற்கு நீங்கள் தகுதியானவர் என்று தெரியுமா?" },
    { role: "user", text: "PMKVY பற்றி சொல்லுங்கள்" },
    { role: "bot", agent: "schemeNavigator", text: "PMKVY (பிரதான் மந்திரி கௌஷல் விகாஸ் யோஜனா) 15–90 நாள் இலவச பயிற்சி + ₹8,000 உதவித்தொகை + அரசு சான்றிதழ் வழங்குகிறது. நான் உங்களுக்காக விண்ணப்பிக்கட்டுமா?" },
  ],
};
